name: Publish Docker Images (Depy)

on:
  workflow_call:
    inputs:
      IMAGE_REGISTRY:
        required: true
        type: string
        default: "ccpgames"
      PYODBC_VERSION:
        required: true
        type: string
      PROTOPLASM_PY_PKG_VERSION:
        required: true
        type: string
    secrets:
      REGISTRY_USER:
        required: true
      REGISTRY_TOKEN:
        required: true

jobs:
  depy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8.18", "3.9.18", "3.10.13", "3.11.8", "3.12.2"]
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set config variable env
        run: |
          DEPY_VERSION=`echo ${{ matrix.python-version }} | cut -d. -f1,2`
          echo "DEPY_VERSION=${DEPY_VERSION}" >> $GITHUB_ENV
          echo "IMG_FULL=${{ inputs.IMAGE_REGISTRY }}/protoplasm:${{ inputs.PROTOPLASM_PY_PKG_VERSION }}-depy${DEPY_VERSION}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/depy/Dockerfile
          network: host
          no-cache: true
          push: true
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            PACKAGE_VERSION=${{ inputs.PROTOPLASM_PY_PKG_VERSION }}
          tags: |
            ${{ env.IMG_FULL }}
            ${{ inputs.IMAGE_REGISTRY }}/protoplasm:latest-depy${{ env.DEPY_VERSION }}

  depy_pyodbc:
    runs-on: ubuntu-latest
    needs: [ depy ]
    strategy:
      matrix:
        depy-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set config variable env
        run: |
          echo "IMG_FULL=${{ inputs.IMAGE_REGISTRY }}/protoplasm:${{ inputs.PROTOPLASM_PY_PKG_VERSION }}-depy${{ matrix.depy-version }}-pyodbc${{ inputs.PYODBC_VERSION }}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/depy/pyodbc.Dockerfile
          network: host
          no-cache: true
          push: true
          build-args: |
            BASE_IMAGE=${{ inputs.IMAGE_REGISTRY }}/protoplasm:${{ inputs.PROTOPLASM_PY_PKG_VERSION }}-depy${{ matrix.depy-version }}
            PYODBC_VERSION=${{ inputs.PYODBC_VERSION }}
          tags: |
            ${{ env.IMG_FULL }}
            ${{ inputs.IMAGE_REGISTRY }}/protoplasm:latest-depy${{ matrix.depy-version }}-pyodbc${{ inputs.PYODBC_VERSION }}
            ${{ inputs.IMAGE_REGISTRY }}/protoplasm:latest-depy${{ matrix.depy-version }}-pyodbc
